data_path: "./data_custom/ours"

experiments:
  - case_name: double_compress_playdoh_test
    category: dough

  - case_name: double_hand_rope_test
    category: rope

  - case_name: double_lift_cloth_test
    category: cloth

  - case_name: double_lift_sloth_test
    category: sloth

  - case_name: double_stretch_dough_test
    category: dough

  - case_name: double_tear_pita_test
    category: bread

  - case_name: single_poke_bluey_test
    category: toy
